# TUGAS
## Pengenalan Array dengan Numpy

Kelompok
1. Surahmat
2. M. Farras
3. Azmi
4. Ryan F
5. Hirzan





In [1]:
# import libraries
import numpy as np

# buat matriks (arr) shape 2x3 dengan tipe data integer 64
arr = np.array ([[1,2,3],
                 [5,6,7]],
                dtype=np.int64)
# [[ 1  2  3 ]
#  [ 5  6  7 ]]

# print arr
print("Matriks arr:")
print(arr)

# print shape arr
print("shape arr:", arr.shape)

# print tipe data arr
print("Tipe data arr:", arr.dtype)


Matriks arr:
[[1 2 3]
 [5 6 7]]
shape arr: (2, 3)
Tipe data arr: int64


In [2]:
# buat matriks (arr_rdm) shape 2x3 dengan tipe data integer 64
import numpy as np

# nilai elemennya random
arr_rdm = np.random.randint(low = 0, high = 20, size=(2,3), dtype = np.int64)

# print arr_rdm
print("Matriks arr_rdm")
print(arr_rdm)

# print shape arr_rdm
print("Shape arr_rdm", arr_rdm.shape)

# print tipe data arr_rdm
print("Tipe data arr_rdm:", arr_rdm.dtype)

Matriks arr_rdm
[[17  2 18]
 [10 16 16]]
Shape arr_rdm (2, 3)
Tipe data arr_rdm: int64


# Aritmatika Dasar dengan Numpy

In [3]:
# operasi penjumlahan arr dan arr_rdm
addition_result = arr +arr_rdm
print("Penjumlah matriks arr dan matriks arr_rdm:")
print(addition_result)

# operasi pengurangan arr dan arr_rdm
subtraction_result = arr - arr_rdm
print ("Pengurangan matriks arr dan matriks arr_rdm:")
print(subtraction_result)

# operasi perpangkatan dua arr_rdm
power_result = arr_rdm **2
print("Perpangkatan arr_rdm:")
print(power_result)

# operasi perkalian elemen-wise arr dan arr_rdm
elementwise_mult_result = arr * arr_rdm
print ("operasi perkalian elemen wise arr & arr_rdm")
print(elementwise_mult_result)

# Transpose matriks arr_rdm
transposed_arr_rdm=arr_rdm.T
print ("Transpose matriks arr_rdm")
print (transposed_arr_rdm)

# operasi perkalian matriks arr dan arr_rdm



Penjumlah matriks arr dan matriks arr_rdm:
[[18  4 21]
 [15 22 23]]
Pengurangan matriks arr dan matriks arr_rdm:
[[-16   0 -15]
 [ -5 -10  -9]]
Perpangkatan arr_rdm:
[[289   4 324]
 [100 256 256]]
operasi perkalian elemen wise arr & arr_rdm
[[ 17   4  54]
 [ 50  96 112]]
Transpose matriks arr_rdm
[[17 10]
 [ 2 16]
 [18 16]]


In [4]:
# print nilai rata-rata arr
mean_all = np.mean(arr)
print(mean_all)

# print nilai rata-rata per baris arr
mean_pear_row = np.mean (arr, axis = 1)
print (mean_pear_row)

# print total nilai seluruh elemen matriks arr
total_sum = np.sum(arr)
print(total_sum)

# print nilai maximal per kolom matriks arr
maxper_colum = np.max(arr, axis=0)
print(maxper_colum)

4.0
[2. 6.]
24
[5 6 7]


# Fitur pada Numpy

In [5]:
# buat array arrg dengan nilai range 1-20
arrg = np.arange(1,21)

# print arrg
print("Array arg:", arrg)

# print nilai arrg index 5
print("Nliai arrg pada indeks 5:", arrg[5])

# print nilai arrg untuk 3 elemen dari terakhir
print("3 elemen dari terakhir arrg:", arrg[-3:])

# print nilai arrg 3 sampai 6
print("Nilai arrg dari indeks 3 sampai 6:", arrg[3:7])

Array arg: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nliai arrg pada indeks 5: 6
3 elemen dari terakhir arrg: [18 19 20]
Nilai arrg dari indeks 3 sampai 6: [4 5 6 7]


In [6]:
# print matriks arr
print(arr)

# print slice matriks arr dengan output
slice_arr = arr[0:3, 1:3]
print("Slice matriks arr:")
print(slice_arr)
## [[ 2  3 ]
##  [ 6  7 ]]

# print slice matriks arr dengan output
slice_arr = arr[:, 2:3]
print("Slice matriks arr:")
print(slice_arr)
## [[ 3 ]
##  [ 7 ]]

[[1 2 3]
 [5 6 7]]
Slice matriks arr:
[[2 3]
 [6 7]]
Slice matriks arr:
[[3]
 [7]]


In [8]:
# buat matriks mtx_rdm ukuran 3x4 dengan tipe data integer, isi elemennya random
mtx_rdm = np.random.randint(low=0, high=100, size=(3, 4), dtype=np.int64)

# print mtx_rdm shape
print("Bentuk awal mtx_rdm:", mtx_rdm.shape)

# ubah shape mtx_rdm menjadi satu dimensi
mtx_rdm_flat = mtx_rdm.flatten()

# ubah shape mtx_rdm menjadi 6x2
mtx_rdm_reshaped = mtx_rdm.reshape(6, 2)
print("Bentuk 6x2 mtx_rdm:", mtx_rdm_reshaped.shape)

Bentuk awal mtx_rdm: (3, 4)
Bentuk 6x2 mtx_rdm: (6, 2)
